version: "1"
rules:                        # Array of rules
  - base: main                # Required. Target branch
    upstream: ohmyzsh:master  # Required. Must be in the same fork network.
    mergeMethod: rebase       # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: false      # Optional, merge pull request even when the mergeable_state is not clean. Default: false

# (https://github.com/wei/pull?tab=readme-ov-file#advanced-setup-with-config)[reference]
#
# ```sh
# git branch -m master main
# git fetch origin
# git branch -u origin/main main
# git remote set-head origin -a
